### ISSUE TITLE
When the media element emits 'error', destroy everything

### ISSUE THREAD

**Issue by feross** [jhiesey/videostream#11]
When an 'error' event is emitted on the `<video>` tag, I expect `videostream` to destroy all it's state and stop doing all work. Instead, it continues to call `popBuffers` in a tight loop (despite the 5ms -> 5s fix I just pushed), printing 1000s of errors to my console in seconds!

I think `videostream` should listen for 'error' on the media element and destroy itself if it's ever emitted.

**Comment by jhiesey** [comment]
Should be fixed
