### ISSUE TITLE
Bitlove Intro video plays, but then throws an error

### ISSUE THREAD

**Issue by feross** [jhiesey/videostream#13]
1. Download the torrent file with `webtorrent-hybrid`:

  ```
  webtorrent-hybrid https://github.com/feross/webtorrent/raw/master/test/torrents/bitlove-intro.torrent --vlc
  ```

2. Drag the [.torrent file](https://github.com/feross/webtorrent/raw/master/test/torrents/bitlove-intro.torrent) onto https://instant.io. If you use `localStorage.debug = "webtorrent:append-to"`, you can see that it falls back to the Blob approach after `videostream` fails.

**Comment by jhiesey** [comment]
Looks like this is actually a webm, file, which isn't supported (yet; may never be).

**Comment by feross** [comment]
Right you are.
