### ISSUE TITLE
Firefox 43 error

### ISSUE THREAD

**Issue by feross** [jhiesey/videostream#17]
Visit https://webtorrent.io with Firefox 43. Video fails to load, and this error is in the console:

"InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable"

Works fine on Firefox Nightly (46). Thoughts?

**Comment by jhiesey** [comment]
Don't know, but I can take a look. Firefox has historically had a pretty buggy MediaSource implementation though, so they could still be ironing things out.

**Comment by feross** [comment]
Yeah, I tested on Firefox 44 and it works fine, so maybe we should just
wait for the next release.

**Comment by jhiesey** [comment]
Works for me. Closing.
