### ISSUE TITLE
Jumping backwards to a different playback position leads to permanent halt of video playback

### ISSUE THREAD

**Issue by triangle42** [jhiesey/videostream#30]
I use videostream to play back the following file https://webtorrent.io/torrents/sintel-1024-surround.mp4.  When I jump back to a different playback position, the video often plays back at first but then stops after a short while. This happens in my own implementation, which uses videostream, as well as when using instant.io for video streaming.

I use Chrome version 51.0.2704.106 m.

**Comment by jhiesey** [comment]
Thanks for letting me know. I'll take a look in the next few days.

**Comment by feross** [comment]
Related discussion: https://github.com/feross/webtorrent/issues/1014#issuecomment-272602561

**Comment by jhiesey** [comment]
This should finally be fixed!
