### ISSUE TITLE
 "GET /built.js" Error (404): "Not found"

### ISSUE THREAD

**Issue by jamiejackherer** [jhiesey/videostream#36]
where is built.js?

**Comment by jamiejackherer** [comment]
ok so i figured its supposed to be index.js, But im trying to play a video file of my own and it still does nothing.. is there any thing we should know in order to get this working?

**Comment by jamiejackherer** [comment]
it simply does not work... after realising its index.js not built.js, it still does not stream a .mp4 file..

**Comment by jhiesey** [comment]
You need to run `npm run build-example` in the top level videostream directory to generate built.js. You'll have to rerun this after any changes to the example code as well.

Then `npm start` should work.

**Comment by jhiesey** [comment]
Please reopen if this is still an issue
