### ISSUE TITLE
add support for m4a playback

### ISSUE THREAD

**Issue by line-o** [jhiesey/videostream#4]
* [x] use audio tag for m4a playback
* [x] allow m4a for file extension
* [x] enable streaming of m4a

**Comment by feross** [comment]
https://instant.io already supports m4v!

**Comment by feross** [comment]
Here are some m4a files that don't work: http://www.bakeraudio.org/sample-audio-recordings.html

We tested "cheeseburger" and "me_myself_i".

**Comment by feross** [comment]
The m4a files on that page seem like they're in a really weird format...

**Comment by feross** [comment]
In any case, https://instant.io now supports .m4a, though not streaming. You need to download the full file first. This is a decent solution for now, but let's obviously leave this issue open :)

**Comment by line-o** [comment]
Cool!

**Comment by line-o** [comment]
If this library is able to stream arbitrary media it might be useful to rename it to mediastream :)

**Comment by jhiesey** [comment]
@line-o good point. I think it'll be limited to video and audio, with audio more of a secondary case. I'm going to keep the name for the moment but may change it if lots of people use it for audio.

What will be a lot harder is supporting non-mp4 formats.

**Comment by line-o** [comment]
Then mp4-streamer might be better :)

**Comment by jakefb** [comment]
Does videostream support H.265 and VP9 codecs? I think YouTube uses VP9 for its 4K video.

**Comment by jhiesey** [comment]
I don't know if it works with H.265 or not, but I doubt that would be hard to get working even if it doesn't.

VP9 typically uses a webm container (similar to MKV) which would take a lot more work to build.

**Comment by jhiesey** [comment]
@feross the audio files in your link use Apple's ALAC codec, which chrome doesn't support, so those probably won't ever work outside safari. I'll try to get some other files that use regular AAC to work instead though.

**Comment by jhiesey** [comment]
At least one .m4a file now works on master. It's the first test file on this page: http://www.thesixteendigital.com/testfiles/

**Comment by jhiesey** [comment]
Closing since I got a file to work properly. I know other files don't work; I'll open a separate issue for that.

**Comment by feross** [comment]
Wohoo!
