### ISSUE TITLE
Publish latest commit to npm

### ISSUE THREAD

**Issue by guanzo** [jhiesey/videostream#48]
Hi, there's a bug in the [render-media](https://github.com/feross/render-media) package that appeared after it upgraded to videostream@3.2.0. 

![bug](https://i.gyazo.com/8d00a4d6935d45f182b9b89bf098c814.png)

The bug went away after testing the code in d8bac5e3b3ea4ea5c864b11ecfa986010b124c2a, so could you publish that commit as a new release? Then I can ping the render-media maintainer to update. Thanks.

**Comment by feross** [comment]
I just published the latest commit to npm as 3.2.1.
